language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_3b24bdad6459_key 
    -iv $encrypted_3b24bdad6459_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - npm install
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy_to_git.sh 'dist' 'git@github.com:qoomon/time-timer-webapp.git' 'gh-pages'
  on:
    branch: master
