language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy_to_git.sh 'dist' "https://${GH_TOKEN}@github.com/qoomon/time-timer-webapp.git" 'gh-pages'
  on:
    branch: master
