language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
install:
  - git config --global user.name "Travis"
  - git config --global user.email '<>'
  - npm install
script:
  - npm run build
  - if [[ "$TRAVIS_BRANCH" =~ ^master$ ]]; then ./push_to_git.sh 'dist' "https://qoomon:${GH_TOKEN}@github.com/qoomon/time-timer-webapp.git" 'gh-pages'; else echo 'ignored.'; fi
